name: JamCade
version: 1.0
main: com.jam2400.jamcade.Main

commands:
   heal:
      description: Heal yourself, specify a player if need be.
      usage: /<command> [player]
      permission: jamcade.heal
   announce:
      description: Announce a message to the server.
      usage: /<command> [message]
      permission: jamcade.announce
   warn:
      description: Warn a player.
      usage: /<command> [player] [reason]
      permission: jamcade.warn
   kick:
      description: Kick a player.
      usage: /<command> [player] [reason]
      permission: jamcade.kick
   msg:
      description: Message a player.
      usage: /<command> [player] [message]
   staff:
      description: Gives a list of online staff members.
      usage: /<command>
   horsify:
      description: Put yourself on a horse.
      usage: /<command>
      permission: jamcade.horsify
   s:
      description: Toggle yourself from receiving notifications, or send a message.
      usage: /<command> <message>
      permission: jamcade.staffmessage
