name: JamCade
version: 1.0
main: com.jam2400.jamcade.Main

commands:
   heal:
      description: Heal yourself, specify a player if need be.
      usage: /<command> [player]
      permission: jamcade.heal
   announce:
      description: Announce a message to the server.
      usage: /<command> [message]
      permission: jamcade.announce
   warn:
      description: Warn a player.
      usage: /<command> [player] [reason]
      permission: jamcade.warn
   kick:
      description: Kick a player.
      usage: /<command> [player] [reason]
      permission: jamcade.kick
   m:
      description: Message a player.
      usage: /<command> [player] [message]
